config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :roles

  get 'results/index'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :articles do
    resources :comments
    collection do
      get :stats
    end
  end

  get 'results', to: 'results#index', as: 'results'
  get 'tags/:tag', to: 'articles#index', as: :tag

  root 'profiles#index'

  resources :users
  resources :groups
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :articles
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :check_permissions
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def check_permissions
      if current_user == nil || !current_user.admin?
        redirect_to root_path, alert: t('group.no_permission')
      end
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:title, :description, user_ids: [])
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= bootstrap_form_for @group do |f| %>

    <% if @group.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@group.errors.count, "error") %></h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @group.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.label t('group.title') %>
  <%= f.text_field :title, hide_label: true %>
  <%= f.label t('group.description') %>
  <%= f.text_field :description, hide_label: true %>
  <%= f.label t('group.users') %>
  <%= f.select :user_ids, User.all.map{|u|[u.nickname, u.id]}, { hide_label: true }, { :multiple => true } %>

  <%= f.submit t('group.save'), :class => 'btn btn-primary' %>
  <%= link_to t('group.cancel'), groups_path, :class => 'btn btn-default' %>

<% end %>

app/views/groups/edit.html.erb
<div class="page-header">
  <h1><%= t('group.edit')  %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/index.html.erb
<div class="page-header">
  <h1><%= t('group.groups') %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('group.title') %></th>
      <th><%= t('group.description') %></th>
      <th><%= t('group.created_at') %></th>
      <th><%= t('group.users') %></th>
      <th><%= t('group.actions') %></th>
    </tr>
  </thead>
  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= link_to group.title, group_path(group) %></td>
        <td><%= group.description %></td>
        <td><%= group.created_at.strftime("%d/%m/%Y %H:%M") %></td>
        <td><%= group.users.map{|user| user.nickname}.join(', ').html_safe %></td>
        <td>
          <%= link_to t('group.edit'),
                      edit_group_path(group), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('group.delete'),
                      group_path(group),
                      :method => :delete,
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('group.new'), new_group_path, :class => 'btn btn-primary' %>

app/views/groups/new.html.erb
<div class="page-header">
  <h1><%=t('group.new') %></h1>
</div>
<%= render :partial => 'form' %>

app/views/groups/show.html.erb
<div class="page-header">
  <h1><%= t('group.label') %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= t('group.title') %>:</strong></dt>
  <dd><%= @group.title %></dd>
  <dt><strong><%= t('group.description') %>:</strong></dt>
  <dd><%= @group.description %></dd>
  <dt><strong><%= t('group.users') %>:</strong></dt>
  <dd><%= @group.users.map{|user| user.nickname}.join(', ').html_safe %></dd>
</dl>

<%= link_to t('group.back'),
              groups_path, :class => 'btn btn-default'  %>
<%= link_to t('group.edit'),
              edit_group_path(@group), :class => 'btn btn-default' %>
<%= link_to t('group.delete'),
              group_path(@group),
              :method => 'delete',
              :class => 'btn btn-danger' %>