config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :roles

  get 'results/index'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :articles do
    resources :comments
    collection do
      get :stats
    end
  end

  get 'results', to: 'results#index', as: 'results'
  get 'tags/:tag', to: 'articles#index', as: :tag

  root 'profiles#index'

  resources :users
  resources :groups
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :check_permissions
  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    @role = Role.find(params[:id])
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
    @role = Role.find(params[:id])
  end

  def create
    @role = Role.new(role_params)
    @role.save
    respond_with(@role)
  end

  def update
    @role = Role.find(params[:id])
    @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    respond_with(@role)
  end

  private
    def check_permissions
      if current_user == nil || !current_user.admin?
        redirect_to root_path, alert: t('role.no_permission')
      end
    end

    def role_params
      params.require(:role).permit(:title, :description, :create_ability, :read_ability, :update_ability, :delete_ability, user_ids: [])
    end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/views/roles/_form.html.erb
<%= bootstrap_form_for @role do |f| %>
    <% if @role.errors.any? %>
        <div class="alert alert-danger alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <h4><%= pluralize(@role.errors.count, "error") %></h4>

          <ul>
            <% @role.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <%= f.label t('role.title') %>
    <%= f.text_field :title, hide_label: true %>
    <%= f.label t('role.description') %>
    <%= f.text_area :description, hide_label: true %>
    <%= f.label t('role.users') %>
    <%= f.select :user_ids, User.all.map { |u| [u.nickname, u.id] }, {hide_label: true}, {:multiple => true} %>
    <%= f.check_box :create_ability, label: t('role.create_ability'), class: "form-control" %>
    <%= f.check_box :read_ability, label: t('role.read_ability'), class: "form-control" %>
    <%= f.check_box :update_ability, label: t('role.update_ability'), class: "form-control" %>
    <%= f.check_box :delete_ability, label: t('role.delete_ability'), class: "form-control" %>
    <%= f.submit t('role.save'), class: "btn btn-primary" %>
<% end %>

app/views/roles/edit.html.erb
<div class="page-header">
  <%= link_to roles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
      <%= t('role.back') %>
  <% end %>
  <%= link_to @role, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
      <%= t('role.show') %>
  <% end %>
  <h1><%= t('role.edit') %></h1>
</div>

<%= render 'form' %>

app/views/roles/index.html.erb
<div class="page-header">
  <%= link_to new_role_path, class: 'btn btn-primary' do %>
      <span class="glyphicon glyphicon-plus"></span>
      <%= t('role.new') %>
  <% end %>
  <h1><%= t('role.roles') %></h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
    <tr>
      <th><%= t('role.title') %></th>
      <th><%= t('role.description') %></th>
      <th><%= t('role.users') %></th>
      <th><%= t('role.create_ability') %></th>
      <th><%= t('role.read_ability') %></th>
      <th><%= t('role.update_ability') %></th>
      <th><%= t('role.delete_ability') %></th>
      <th></th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <%= content_tag_for(:tr, @roles) do |role| %>
        <td><%= link_to role.title, role_path(role) %></td>
        <td><%= role.description %></td>
        <td><%= role.users.map { |user| user.nickname }.join(', ').html_safe %></td>
        <td>
          <% if role.create_ability %>
              <span class="glyphicon glyphicon-plus"></span>
          <% else %>
              <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
        <td>
          <% if role.read_ability %>
              <span class="glyphicon glyphicon-plus"></span>
          <% else %>
              <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
        <td>
          <% if role.update_ability %>
              <span class="glyphicon glyphicon-plus"></span>
          <% else %>
              <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>
        <td>
          <% if role.delete_ability %>
              <span class="glyphicon glyphicon-plus"></span>
          <% else %>
              <span class="glyphicon glyphicon-minus"></span>
          <% end %>
        </td>

        <td><%= link_to t('role.edit'), edit_role_path(role) %></td>
        <td><%= link_to t('role.delete'), role, method: :delete %></td>
    <% end %>
    </tbody>
  </table>
</div>

app/views/roles/new.html.erb
<div class="page-header">
  <%= link_to roles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
      <%= t('role.back') %>
  <% end %>
  <h1><%= t('role.new') %></h1>
</div>

<%= render 'form' %>

app/views/roles/show.html.erb
<div class="page-header">
  <%= link_to roles_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
      <%= t('role.back') %>
  <% end %>
  <%= link_to edit_role_path(@role), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
      <%= t('role.edit') %>
  <% end %>
  <h1><%= t('role.label') %></h1>
</div>

<dl class="dl-horizontal">
  <dt><%= t('role.title') %>:</dt>
  <dd><%= @role.title %></dd>

  <dt><%= t('role.description') %>:</dt>
  <dd><%= @role.description %></dd>
  
  <dt><%= t('role.users') %>:</dt>
  <dd><%= @role.users.map{|user| user.nickname}.join(', ').html_safe %></dd>

  <dt><%= t('role.create_ability') %>:</dt>
  <dd>
  <% if @role.create_ability %>
  <span class="glyphicon glyphicon-plus"></span>          
  <% else %>
  <span class="glyphicon glyphicon-minus"></span>
  <% end %>
  </dd>

  <dt><%= t('role.read_ability') %>:</dt>
  <dd>
  <% if @role.read_ability %>
  <span class="glyphicon glyphicon-plus"></span>          
  <% else %>
  <span class="glyphicon glyphicon-minus"></span>
  <% end %>
  </dd>

  <dt><%= t('role.update_ability') %>:</dt>
  <dd>
  <% if @role.update_ability %>
  <span class="glyphicon glyphicon-plus"></span>          
  <% else %>
  <span class="glyphicon glyphicon-minus"></span>
  <% end %>
  </dd>

  <dt><%= t('role.delete_ability') %>:</dt>
  <dd>
  <% if @role.delete_ability %>
  <span class="glyphicon glyphicon-plus"></span>          
  <% else %>
  <span class="glyphicon glyphicon-minus"></span>
  <% end %>
  </dd>

</dl>