config/routes.rb
Rails.application.routes.draw do

  resources :profiles

  resources :roles

  get 'results/index'

  devise_for :users, controllers: { registrations: "users/registrations" }
  resources :articles do
    resources :comments
    collection do
      get :stats
    end
  end

  get 'results', to: 'results#index', as: 'results'
  get 'tags/:tag', to: 'articles#index', as: :tag

  root 'profiles#index'

  resources :users
  resources :groups
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
            length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_and_belongs_to_many :articles
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  validates :name, presence: true
  validates :name, uniqueness: true
  validates :name, length: { minimum: 5 }
  validates :description, presence: true
  validates :lng, presence: true
  validates :lat, presence: true
  validates :rating, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5
  }
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :articles
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :get_user_article, only: [:edit, :update, :destroy]

  def index
    user_articles = Article.where(id: current_user.article_ids)
    if params[:user_id]
      @articles = user_articles.where(:user_id => params[:user_id])
    elsif params[:tag]
      @articles = user_articles.tagged_with(params[:tag])
    else
      @articles = user_articles
    end
    @articles = @articles.paginate(:page => params[:page]).order('created_at DESC')

  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.new(article_params)
    @article.groups = current_user.groups

    if verify_recaptcha(model: @article) && @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
  end

  def update
    if verify_recaptcha(model: @article) && @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
     @article.destroy
     @article.groups.clear
     redirect_to articles_path
  end

  def stats
    @stats = Hash.new
    @stats[:article_count] = Article.group_by_month(:created_at).count
    @stats[:user_count] = User.group_by_month(:created_at).count
    @stats[:article_by_user] = Article.group(:user_id).count.map { |key, value|
      [User.find(key).nickname, value]
    }
    @stats[:article_by_comment] = Comment.group(:article_id).count.map { |key, value|
      article = Article.find(key)
      ["#{article.title.truncate(15, separator: ' ')}, #{User.find(article.user_id).nickname}", value]
    }
  end

  private
  def article_params
    params.require(:article).permit(:title, :text, :user_id, :tag_list)
  end

  def get_user_article
    @article = Article.find(params[:id])
    if current_user != @article.user
      redirect_to @article, alert: t('post.alert.permissions')
    end
  end

end

WillPaginate.per_page = 5

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :check_permissions
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @groups = Group.all
    respond_with(@groups)
  end

  def show
    respond_with(@group)
  end

  def new
    @group = Group.new
    respond_with(@group)
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    @group.save
    respond_with(@group)
  end

  def update
    @group.update(group_params)
    respond_with(@group)
  end

  def destroy
    @group.destroy
    respond_with(@group)
  end

  private
    def check_permissions
      if current_user == nil || !current_user.admin?
        redirect_to root_path, alert: t('group.no_permission')
      end
    end

    def set_group
      @group = Group.find(params[:id])
    end

    def group_params
      params.require(:group).permit(:title, :description, user_ids: [])
    end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @search_results = Article.search_everywhere(params[:query])
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_filter :check_permissions
  respond_to :html

  def index
    @roles = Role.all
    respond_with(@roles)
  end

  def show
    @role = Role.find(params[:id])
    respond_with(@role)
  end

  def new
    @role = Role.new
    respond_with(@role)
  end

  def edit
    @role = Role.find(params[:id])
  end

  def create
    @role = Role.new(role_params)
    @role.save
    respond_with(@role)
  end

  def update
    @role = Role.find(params[:id])
    @role.update(role_params)
    respond_with(@role)
  end

  def destroy
    @role = Role.find(params[:id])
    @role.destroy
    respond_with(@role)
  end

  private
    def check_permissions
      if current_user == nil || !current_user.admin?
        redirect_to root_path, alert: t('role.no_permission')
      end
    end

    def role_params
      params.require(:role).permit(:title, :description, :create_ability, :read_ability, :update_ability, :delete_ability, user_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :check_permissions, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if current_user != @user
      @user.destroy
    else
      redirect_to users_path, alert: t('user.delete_own')
    end
    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :nickname, :location)
  end

  def check_permissions
    if current_user == nil || !current_user.admin?
      redirect_to users_path, alert: t('user.no_permission')
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraduateWork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "http://www.google.com/jsapi", "chartkick" %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'GraduateWork', root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to t(:show_all_posts), articles_path %></li>
            <li><%= link_to t(:show_all_profiles), profiles_path %></li>
          </ul>

          <%= form_tag results_path, method: :get, role: 'search', class:"navbar-form navbar-left" do %>
              <div class="form-group">
                <%= text_field_tag :query, params[:query], placeholder: t('search.placeholder'),
                                   class: "form-control", style: "height: inherit;" %>
              </div>
              <%= submit_tag t('search.submit'), class:"btn btn-success" %>
          <% end %>


          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
                <li><a href="#"><%= current_user.email %></a></li>
                <li><%= link_to t(:sign_out), destroy_user_session_path, :method => :delete %></li>
            <% else %>
                <li><%= link_to t(:sign_in), new_user_session_path %></li>
                <li><%= link_to t(:sign_up), new_user_registration_path %></li>
            <% end %>
          </ul>

        </div>
      </div>
</nav>

    <div class="container">
      <% if notice %>
          <div class="alert alert-success" role="alert"><%= notice %></div>
      <% end %>
      <% if alert %>
          <div class="alert alert-danger" role="alert"><%= alert %></div>
      <% end %>

      <%= yield %>
    </div>

    <footer class="footer">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="text-muted"><%= t(:company)%></li>
          <li class="btn"><%= link_to t(:stats), stats_articles_path %></li>
          <li class="btn"><%= link_to t('user.link'), users_path %></li>
          <% if current_user && current_user.admin? %>
            <li class="btn"><%= link_to t('group.link'), groups_path %></li>
            <li class="btn"><%= link_to t('role.link'), roles_path %></li>
          <% end %>


        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="btn"><a href="?locale=ru"><%= t(:russian_menu)%></a></li>
          <li class="btn"><a href="?locale=en"><%= t(:english_menu)%></a></li>
        </ul>
      </div>
    </footer>

</body>
</html>